security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 3600000
spring:
  application:
    name: SoBarba
  security:
    user:
      name: user
      password: unodevstest
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/sobarba
    username: postgres
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
    hiraki:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: prd
server:
  port: ${PORT:8080}
port: 5173
logging:
  level:
    root: WARN