spring:
  application:
    name: SoBarba
  security:
    user:
      name: user
      password: unodevstest
server:
  port: 8081
port: 5173
springdoc:
  api-docs:
    path: /sobarba-api
  swagger-ui:
    path: /sobarba-docs
