security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 3600000
spring:
  application:
    name: SoBarba
  security:
    user:
      name: user
      password: unodevstest
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/sobarba
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: prd
server:
  port: 8081
port: 5173
springdoc:
  api-docs:
    path: /sobarba-api
  swagger-ui:
    path: /sobarba-docs
